### ISSUE TITLE
No such file or directory when running `read_splits`

### ISSUE THREAD

**Issue by lucasdavid** [lplnufpi/essay-br#1]
Hello. Thank you for your contribution.
I'm getting the following error after running the code:
```py
>>> c = Corpus()
>>> train, valid, test = c.read_splits()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
  File "/envs/torch/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'splits/train.csv'
```

Am I right to assume I should just download these files from the [essay](https://github.com/rafaelanchieta/essay) repository and rename them to train.csv, dev.csv and test.csv here?

Thank you very much.

**Comment by rafaelanchieta** [comment]
Hi Lucas.

I just updated the repository.
First of all, you need to build the corpus.
`Corpus().build_corpus('extended_essay-br.csv')`
This method is responsible to generate the splits.

Then, you can read the splits.
`train, valid, test = Corpus().read_splits()`
`print(test.head())`

**Comment by lucasdavid** [comment]
Right. It's working like a charm with either that or by running `python build_dataset.py`.
Thank you very much!
